name: Backend CD
on:
  push:
    branches: 
      - slbin-park-patch-1

jobs:
  deploy:
    #테스트
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 Checkout
        uses: actions/checkout@v3

      - name: Set Yaml #yml 설치
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yml
        env:
          spring.redis.host : ${{secrets.HOME_HOST}}
          spring.redis.port : ${{DB_REDIS_PORT}}
          spring.datasource.url: ${{ secrets.DB_URL }}
          spring.datasource.username: ${{ secrets.DB_USER_NAME }}
          spring.datasource.password: ${{ secrets.DB_USER_PASSWORD }}

      - name: 스프링부트 애플리케이션 빌드 # (1)
        run: ./gradlew build
          
      - name: 도커 이미지 빌드 # (2)
        run: docker build -t slbin/one-touch-popol-dev .
      - name: Docker Hub 로그인 # (3)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Hub 퍼블리시 # (4)
        run: docker push slbin/one-touch-popol-dev 
      - name: WAS 인스턴스 접속 및 애플리케이션 실행 # (5)
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOME_HOST }}
          username: ${{ secrets.HOME_USERNAME }}
          password: ${{ secrets.HOME_PASSWORD }}
          port: ${{ secrets.HOME_SSH_PORT }}
          script: |
            docker stop one-touch-popol-dev
            docker rm one-touch-popol-dev 
            docker pull slbin/one-touch-popol-dev
            docker run -d -p ${{ secrets.SPRING_PORT }}:${{ secrets.SPRING_PORT }} --name one-touch-popol-dev ${{ secrets.HOME_USERNAME }}/one-touch-popol-dev 
